export {default as Price} from './Price'
export {default as SearchInput} from './SearchInput'
export {default as Logo} from './Logo'
export {default as Title} from './Title'
export {default as BackToTop} from './BackToTop'
